### ISSUE TITLE
link in readme wrong

### ISSUE THREAD

**Issue by jasperkrab** [geertmeersman/energie-meter#1]
The link for the Infrared Reflective Sensor isn't correct. 

P.S
Thank you for the reference, could you share your experience? Looks like this would work fine without any misreadings.

**Comment by geertmeersman** [comment]
Thanks!
Well it's up and running now since December and all good. 
There are rare cases (happened twice) that the mirror stops just on the edge, and that the reflection goes crazy, but for me that's acceptable.  The readings are very accurate and again, it's the goal  to have a monitoring, not replacing the actual meter.

**Comment by geertmeersman** [comment]
This is the "final" setup:

![image](https://user-images.githubusercontent.com/1844091/219370828-7eca917c-c2a6-4074-b2e0-7d50578eea01.png)
